[workspace]
members = [ "hk-dispatcher", "hk-trading" ]
resolver = "2"

[workspace.dependencies]
tracing = "0.1.40"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
protobuf = { version = "3.4.0", features = ["with-bytes"] }
protobuf-codegen = "3.4.0"
