[tasks.wasm_build]
script_runner = "bash"
script = [
    """
    #!/bin/bash
    BASE_DIR=$(pwd)
    crates=( "hk-trading" )

    # Iterate over each crate and build it
    for crate in "${crates[@]}"; do
      echo "🔥🔥🔥  Building $crate with wasm-pack..."
      cd "$BASE_DIR/rust-lib/$crate" || { echo "Failed to enter directory $crate"; exit 1; }

      wasm-pack build --target web || { echo "Build failed for $crate"; exit 1; }
    done
    """
]

[tasks.web-chart-start]
script_runner = "bash"
script = '''
cd rust-lib/web_chart
trunk serve --open
'''

[tasks.web-chart-css]
script = '''
cd rust-lib/web_chart
stylance --watch --output-file ./styles/bundle.css . 
'''